services:
  todo-backend:           # The name of the service, can be anything
    image: express-server # Declares which image to use
    build:
      context: ./todo-backend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    ports:                # Declares the ports to publish
      - 3001:3000
    container_name: todo-backend-dev # This will name the container todo-backend-dev
    environment: 
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis
    depends_on:
      - "mongo"
      - "redis"
  mongo:
    image: mongo
    #ports:
    # - 3456:27017
    expose: 
      - 27017
    container_name: todo-mongo-dev # This will name the container todo-mongo-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  redis:
    image: redis
    expose: 
      - 6379
    # Everything else
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    container_name: todo-redis-dev # This will name the container todo-redis-dev
    volumes: # Declare the volume
      - ./todo-backend/redis_data:/data

  todo-frontend:
    image: react-ui
    build:
      context: ./todo-frontend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./todo-frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3210:3000
    container_name: todo-frontend-dev # This will name the container todo-frontend-dev
    environment:
      #- REACT_APP_BACKEND_URL=http://todo-backend:3001
      - REACT_APP_BACKEND_URL=http://localhost:3001/

  debug-helper:
    image: busybox

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - "todo-backend"
      - "todo-frontend"